### PR TITLE
Add the latest changes from upstream

### PR DESCRIPTION
**Pull request by Apurrvv**
### Description

Update the Octomap according to the latest main

### Motivation and Context

We want to lock the repositories.

### How Has This Been Tested?

Used the module as a dependency with caission_ros_pkg

### Checklist

- [x] Have you filled the sections above?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same GitHub Issues/ClickUp Task(s)?
- [x] Have you documented the changes in GitHub Issues and/or ClickUp Task(s) related to this Pull Request?
- [x] Have you added labels, where appropriate, to this Pull Request?

### CODE REVIEW

**Comment by meisamhasani-dx** [comment]
@Apurrvv Can you please link the task, and add a summary of reasons for the changes in the code?

**Comment by Apurrvv** [comment]
> @Apurrvv Can you please link the task, and add a summary of reasons for the changes in the code?

We have used an open-source repository for [octomap](https://github.com/iKrishneel/octomap_server2). In a recent discussion, it was decided that we will lock the perception dependencies. 
We had a forked version of octomap inside Deepx this PR is to update the forked version to the latest changes from upstream.

Here are two ClickUp tasks related to this task: - 
1. https://app.clickup.com/t/864dqf99x
2. https://app.clickup.com/t/864dr3dtn

**Comment by Apurrvv** [comment]
Regarding code changes, I don't have much of an idea but they mostly look like changes related to removing some function that is not going to create any major functionality change. So I think it is safe to merge.

**Comment by meisamhasani-dx** [comment]
> Regarding code changes, I don't have much of an idea but they mostly look like changes related to removing some function that is not going to create any major functionality change. So I think it is safe to merge.

So you just merged the main repo to the forked one, right? I thought you removed some functions by yourself which I didn't understand why.

**Comment by Apurrvv** [comment]
> > Regarding code changes, I don't have much of an idea but they mostly look like changes related to removing some function that is not going to create any major functionality change. So I think it is safe to merge.
> 
> So you just merged the main repo to the forked one, right? I thought you removed some functions by yourself which I didn't understand why.

No, I didn't remove anything on my own. The changes are coming from upstream.

**Comment by zey1an** [comment]
@Apurrvv After changing , Did you test it with perception pipeline  ?

**Comment by Apurrvv** [comment]
> @Apurrvv After changing , Did you test it with perception pipeline ?

Yes, I have tested it with the perception pipeline.

**Comment by meisamhasani-dx** [comment]
> > @Apurrvv After changing , Did you test it with perception pipeline ?
> 
> Yes, I have tested it with the perception pipeline.

In testing with caisson what have you wrote for[ the version here](https://github.com/DeepX-inc/caisson_ros_pkg/blob/0045dfe75fdcbdf90cd111034a39ca7b88bad15c/third_party.repos#L17)? That's the only block you changed in caisson system?

**Comment by Apurrvv** [comment]
> > > @Apurrvv After changing , Did you test it with perception pipeline ?
> > 
> > 
> > Yes, I have tested it with the perception pipeline.
> 
> In testing with caisson what have you wrote for[ the version here](https://github.com/DeepX-inc/caisson_ros_pkg/blob/0045dfe75fdcbdf90cd111034a39ca7b88bad15c/third_party.repos#L17)? That's the only block you changed in caisson system?

No there is one more change w.r.t to perception common - [link](https://github.com/DeepX-inc/caisson_ros_pkg/blob/0396f5584db19ab7deddc25d80ca8bfbe22ce76a/deepx.repos#L29)

**Comment by meisamhasani-dx** [comment]
> > > > @Apurrvv After changing , Did you test it with perception pipeline ?
> > > 
> > > 
> > > Yes, I have tested it with the perception pipeline.
> > 
> > 
> > In testing with caisson what have you wrote for[ the version here](https://github.com/DeepX-inc/caisson_ros_pkg/blob/0045dfe75fdcbdf90cd111034a39ca7b88bad15c/third_party.repos#L17)? That's the only block you changed in caisson system?
> 
> No there is one more change w.r.t to perception common - [link](https://github.com/DeepX-inc/caisson_ros_pkg/blob/0396f5584db19ab7deddc25d80ca8bfbe22ce76a/deepx.repos#L29)

So I guess, you should also have the relative change in the caisson system as a PR and link these two together.

**Comment by Apurrvv** [comment]
> > > > > @Apurrvv After changing , Did you test it with perception pipeline ?
> > > > 
> > > > 
> > > > Yes, I have tested it with the perception pipeline.
> > > 
> > > 
> > > In testing with caisson what have you wrote for[ the version here](https://github.com/DeepX-inc/caisson_ros_pkg/blob/0045dfe75fdcbdf90cd111034a39ca7b88bad15c/third_party.repos#L17)? That's the only block you changed in caisson system?
> > 
> > 
> > No there is one more change w.r.t to perception common - [link](https://github.com/DeepX-inc/caisson_ros_pkg/blob/0396f5584db19ab7deddc25d80ca8bfbe22ce76a/deepx.repos#L29)
> 
> So I guess, you should also have the relative changes in the caisson system as a PR and link these two together.

Yes - https://github.com/DeepX-inc/caisson_ros_pkg/pull/476

**Review by meisamhasani-dx — APPROVED** [review]
I have [tested the pkg](https://app.clickup.com/t/864dud7z0?comment=90070003655617) and it's working good.

**Pull request merged**
